Support command line parameters in benchmarks
kokkos/kokkos-kernels pull request #1760
Opened 2023-03-30 14:02 UTC by cz4rs

Support command line parameters matching the behavior of original performance tests as closely as possible.

Sample output (console):
```
./build/perf_test/KokkosKernels_PerformanceTest_Benchmark --benchmark_format=console --benchmark_counters_tabular=true --m 99 --n 3 --repeat 2 --benchmark_filter=Blas1_dot_mv --use_openmp 1
```
```
Running ./build/perf_test/KokkosKernels_PerformanceTest_Benchmark
(...)
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations Avg DOT FLOP/s: Avg DOT time (s):     OpenMP  Params::m  Params::n Params::repeat Params::use_cuda Params::use_hip Params::use_openmp Params::use_sycl Params::use_threads
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Blas1_dot_mv<double>/manual_time      0.000 s         0.000 s         44468         85.443M            6.952u          1         99          3              2                0               0                  1                0                   0
```

Sample output (json):
```json
{
  "context": {
    "date": "2023-03-30T16:02:10+02:00",
    "host_name": "rysy",
    "executable": "./build/perf_test/KokkosKernels_PerformanceTest_Benchmark",
    "num_cpus": 8,
    "mhz_per_cpu": 4700,
    "cpu_scaling_enabled": true,
    "caches": [
      {
        "type": "Data",
        "level": 1,
        "size": 32768,
        "num_sharing": 1
      },
      {
        "type": "Instruction",
        "level": 1,
        "size": 32768,
        "num_sharing": 1
      },
      {
        "type": "Unified",
        "level": 2,
        "size": 262144,
        "num_sharing": 1
      },
      {
        "type": "Unified",
        "level": 3,
        "size": 12582912,
        "num_sharing": 8
      }
    ],
    "load_avg": [0.586914,0.986816,1.07178],
    "library_build_type": "debug",
    "CPU architecture": "none",
    "Default Device": "N6Kokkos6OpenMPE",
    "GIT_BRANCH": "benchmark-command-line-params",
    "GIT_CLEAN_STATUS": "CLEAN",
    "GIT_COMMIT_DATE": "2023-03-30T15:57:56+02:00",
    "GIT_COMMIT_DESCRIPTION": "Parse command line parameters",
    "GIT_COMMIT_HASH": "f58c6469f",
    "GOOGLE_BENCHMARK_VERSION": "1.6.2",
    "GPU architecture": "none",
    "KOKKOSKERNELS_ENABLE_TPL_ARMPL": "no",
    "KOKKOSKERNELS_ENABLE_TPL_BLAS": "no",
    "KOKKOSKERNELS_ENABLE_TPL_CBLAS": "no",
    "KOKKOSKERNELS_ENABLE_TPL_CHOLMOD": "no",
    "KOKKOSKERNELS_ENABLE_TPL_CUBLAS": "no",
    "KOKKOSKERNELS_ENABLE_TPL_CUSPARSE": "no",
    "KOKKOSKERNELS_ENABLE_TPL_LAPACK": "no",
    "KOKKOSKERNELS_ENABLE_TPL_LAPACKE": "no",
    "KOKKOSKERNELS_ENABLE_TPL_MAGMA": "no",
    "KOKKOSKERNELS_ENABLE_TPL_METIS": "no",
    "KOKKOSKERNELS_ENABLE_TPL_MKL": "no",
    "KOKKOSKERNELS_ENABLE_TPL_ROCBLAS": "no",
    "KOKKOSKERNELS_ENABLE_TPL_ROCSPARSE": "no",
    "KOKKOSKERNELS_ENABLE_TPL_SUPERLU": "no",
    "KOKKOS_COMPILER_CLANG": "1507",
    "KOKKOS_ENABLE_ASM": "no",
    "KOKKOS_ENABLE_CXX17": "yes",
    "KOKKOS_ENABLE_CXX20": "no",
    "KOKKOS_ENABLE_CXX23": "no",
    "KOKKOS_ENABLE_DEBUG_BOUNDS_CHECK": "yes",
    "KOKKOS_ENABLE_GNU_ATOMICS": "no",
    "KOKKOS_ENABLE_HBWSPACE": "no",
    "KOKKOS_ENABLE_HWLOC": "yes",
    "KOKKOS_ENABLE_INTEL_ATOMICS": "no",
    "KOKKOS_ENABLE_INTEL_MM_ALLOC": "no",
    "KOKKOS_ENABLE_LIBDL": "yes",
    "KOKKOS_ENABLE_LIBRT": "no",
    "KOKKOS_ENABLE_OPENMP": "yes",
    "KOKKOS_ENABLE_OPENMP_ATOMICS": "no",
    "KOKKOS_ENABLE_PRAGMA_IVDEP": "no",
    "KOKKOS_ENABLE_PRAGMA_LOOPCOUNT": "no",
    "KOKKOS_ENABLE_PRAGMA_UNROLL": "no",
    "KOKKOS_ENABLE_PRAGMA_VECTOR": "no",
    "KOKKOS_ENABLE_SERIAL": "yes",
    "KOKKOS_ENABLE_SERIAL_ATOMICS": "no",
    "KOKKOS_ENABLE_WINDOWS_ATOMICS": "no",
    "Kokkos": "OpenMP thread_pool_topology[ 1 x 8 x 1 ]",
    "Kokkos Version": "4.0.0",
    "KokkosKernels Version": "4.0.99"
  },
  "benchmarks": [
    {
      "name": "Blas1_dot_mv<double>/manual_time",
      "family_index": 0,
      "per_family_instance_index": 0,
      "run_name": "Blas1_dot_mv<double>/manual_time",
      "run_type": "iteration",
      "repetitions": 1,
      "repetition_index": 0,
      "threads": 1,
      "iterations": 44285,
      "real_time": 1.5161024026193994e-05,
      "cpu_time": 2.3002449520153550e-05,
      "time_unit": "s",
      "Avg DOT FLOP/s:": 8.5566119273984447e+07,
      "Avg DOT time (s):": 6.9419999999999998e-06,
      "OpenMP": 1.0000000000000000e+00,
      "Params::m": 9.9000000000000000e+01,
      "Params::n": 3.0000000000000000e+00,
      "Params::repeat": 2.0000000000000000e+00,
      "Params::use_cuda": 1.0000000000000000e+00,
      "Params::use_hip": 0.0000000000000000e+00,
      "Params::use_openmp": 1.0000000000000000e+00,
      "Params::use_sycl": 0.0000000000000000e+00,
      "Params::use_threads": 0.0000000000000000e+00
    }
  ]
}
```

Error when requesting unavailable `ExecSpace`:
```
Running ./build/perf_test/KokkosKernels_PerformanceTest_Benchmark
(...)
---------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations
---------------------------------------------------------------------------
Blas1_dot_mv<double>/manual_time ERROR OCCURRED: 'CUDA requested, but not available.'
```

2023-03-30 14:56 UTC, lucbv requested changes
This needs to be discussed, I think this design is bad and will lead to a lot of trouble down the road when the benchmarks are more complex than Blas.

2023-03-30 14:56 UTC, lucbv commented on perf_test/Benchmark_Context.hpp
> +      params_[argv[i]] = std::atoi(argv[i + 1]);
How do you know every parameter will always be an `int` and not a `bool`, a string or a floating point values?
Maybe this should be called `parse_int_inputs` and additional version should be added for other types?

2023-03-30 14:56 UTC, lucbv commented on perf_test/Benchmark_Context.hpp
> +  static int get_param_or_default(std::string param, int default_value) {
Same as above

2023-03-30 14:56 UTC, lucbv commented on perf_test/Benchmark_Context.hpp
> +    for (int i = 1; i < argc; i += 2) {
This assumes something about all the arguments being of the form `--option value` and none being of the form `--use_option`

2023-03-30 15:56 UTC, cz4rs commented
> This needs to be discussed, I think this design is bad and will lead to a lot of trouble down the road when the benchmarks are more complex than Blas.

I agree on the need for more general approach. This is matching current implementation for Blas_dot_mv:
https://github.com/kokkos/kokkos-kernels/blob/b079a4e2dd76de85e9024cb5c447cdb2b3c1293b/perf_test/blas/blas1/KokkosBlas_dot_mv_perf_test.cpp#L53-L85

The one that is probably most complex amongst Blas tests is `KokkosBlas3_perf_test.cpp`:
https://github.com/kokkos/kokkos-kernels/blob/b079a4e2dd76de85e9024cb5c447cdb2b3c1293b/perf_test/blas/blas3/KokkosBlas3_perf_test.cpp#L25-L28
https://github.com/kokkos/kokkos-kernels/blob/b079a4e2dd76de85e9024cb5c447cdb2b3c1293b/perf_test/blas/blas3/KokkosBlas3_perf_test.cpp#L276-L298

2023-03-31 06:37 UTC, kokkos-devops-admin commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

2023-04-07 15:02 UTC, cz4rs commented
Closing as the preferred approach was merged with #1754.

2023-04-07 15:02 UTC, closed without merging