Implement batched serial getrf
kokkos/kokkos-kernels pull request #2331
Opened 2024-09-10 07:44 UTC by yasahi-hpc

This PR implements [getrf](https://www.netlib.org/lapack/explore-html-3.6.1/dd/d9a/group__double_g_ecomputational_ga0019443faea08275ca60a734d0593e60.html) function.

Following files are added:
1. `KokkosBatched_Getrf_Serial_Impl.hpp`: Internal interfaces with implementation details
2. `KokkosBatched_Getrf.hpp`: APIs
3. `Test_Batched_SerialGetrf.hpp`: Unit tests for that

## Detailed description
It computes an LU factorization of a real general M-by-N matrix `A` using partial pivoting with row interchanges.
Here, the matrix has the following shape.
- `A`: `(batch_count, m, n)`  
  On entry, the M-by-N matrix to be factored. On exit, the factors `L` and `U` from the factorization
  `A = P * L * U`; the unit diagonal elements of `L` are not stored.
- `IPIV`: `(batch_count, min(m, n))`
  The pivot indices; for `0 <= i < min(M,N)`, row `i` of the matrix was interchanged with row `IPIV(i)`.

Parallelization would be made in the following manner. This is efficient only when 
A is given in `LayoutLeft` for GPUs and `LayoutRight` for CPUs (parallelized over batch direction).

```C++
Kokkos::parallel_for('getrf', 
    Kokkos::RangePolicy<execution_space> policy(0, n),
    [=](const int k) {
        auto aa = Kokkos::subview(_a, k, Kokkos::ALL(), Kokkos::ALL());
        auto ipiv = Kokkos::subview(_ipiv, k, Kokkos::ALL());

        KokkosBatched::SerialGetrf<AlgoTagType>::invoke(aa, ipiv);
    });
```

## Tests
1.  Make a random matrix from random `A` and factorize it into `LU` with `ipiv`. Reconstruct `L` and `U` from `LU`. Then permute `A` by `ipiv` and confirm `LU` == `A`.
1.  Simple and small analytical test, i.e. choose `A` as follows to confirm `LU` == `A`.
```bash
A = [[1. 0. 0. 0.],
     [0. 1. 0. 0.],
     [0. 0. 1. 0.],
     [0. 0. 0. 1.]]
LU = [[1. 0. 0. 0.],
      [0. 1. 0. 0.],
      [0. 0. 1. 0.],
      [0. 0. 0. 1.]]
piv = [0 1 2 3]
```

## Important remarks
1. We have different implementations for CPUs and GPUs. For CPUs, we employ the original implementation with recursion. For GPUs, we use a static stack to achieve recursive calls. Device level recursion did not work appropriately. 
2. We need to add helper functions `Laswp` and `Iamax`. These are also used for `getrs` and `gbtrf`.
3. In the current implementation, the maximum A size is `4096 x 4096 (=2^12)` due to the limit of the stack size. In order to avoid this limit, we need to ask user to prepare a temporal buffer to achieve a stack. 
4. Currently, we call CPU version if View is accessible from host. This does not work appropriately if we execute the function on GPUs with USM.
5. For the complex matrix, we need to implement the complex versions of `trsm` and `gemm` first.

2024-09-10 08:06 UTC, kokkos-devops-admin commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO INSPECTION HAS BEEN PERFORMED ON THIS PULL REQUEST! - This PR must be inspected by setting label 'AT: PRE-TEST INSPECTED'.

2025-01-06 17:14 UTC, cwpearson requested changes

2025-01-06 17:14 UTC, cwpearson commented on batched/dense/unit_test/Test_Batched_SerialGetrf.hpp
> +using namespace KokkosBatched;
Since these headers get included into a big test file, I'd rather not pollute the global namespace.

2025-01-07 05:01 UTC, yasahi-hpc commented on batched/dense/unit_test/Test_Batched_SerialGetrf.hpp
> +using namespace KokkosBatched;
Makes sense. I have fixed accordingly.

2025-01-07 05:10 UTC, yasahi-hpc commented
@cwpearson Thank you for the review. I have updated based on your review. Further reviews are highly appreciated

2025-01-08 05:55 UTC, yasahi-hpc commented on batched/dense/impl/KokkosBatched_Getrf_Serial_Internal.hpp
> +    //        [ A00 ]
Sorry for the confusion. Here, A0 is equivalent to

```
[ A00 ]
[ --- ]
[ A10 ]
```

I have added the concrete explanation in the docstrings of `KokkosBatched_Getrf.hpp`. For consistency, I changed the matrix notation in a pythonic manner, i.e., 

```
A0 = [[A00],
      [A10]]
```

The original is coming from the lapack notation
https://www.netlib.org/lapack/explore-html-3.6.1/dd/d9a/group__double_g_ecomputational_gabdd3af29e9f6bbaf4b352341a1e8b464.html#gabdd3af29e9f6bbaf4b352341a1e8b464

2025-01-08 05:57 UTC, yasahi-hpc commented on batched/dense/unit_test/Test_Batched_SerialGetrf.hpp
> +  test_batched_getrf<TestDevice, float, algo_tag_type>();
Sure. 
I added a little more complicated analytical test where we know all of the matrices that satisfy
`PA = LU`

2025-01-13 14:37 UTC, lucbv approved these changes

2025-01-13 14:37 UTC, merged