batched - dense: Testing and fixing Serial QR
kokkos/kokkos-kernels pull request #2342
Opened 2024-09-19 19:45 UTC by lucbv

The serial QR algorithms does not have unit-tests and is failing for non square matrices. See issue #2328.
This first commit fixes the issue with rectangular matrices and adds a basic test for that use case.
Next will work on adding a test that exercises the interfaces on multiple matrices of different sizes within a parallel_for. Finally equivalent tests will be added for the square case as well.

Tasks:

- [ ] analytical test on rectangular matrix (SerialQR, ApplyQ, FormQ, Q*Q^t=I)
  - [ ] SerialQR
  - [ ] ApplyQ
  - [ ] FormQ
- [ ] multiple variable size rectangular matrices (same API as above)
  - [ ] SerialQR
  - [ ] ApplyQ
  - [ ] FormQ
- [ ] analytical test on square matrix
  - [ ] SerialQR
  - [ ] ApplyQ
  - [ ] FormQ
- [ ] multiple variable size square matrices
  - [ ] SerialQR
  - [ ] ApplyQ
  - [ ] FormQ

2024-10-10 15:05 UTC, cwpearson requested changes
edit - duplicated comment

2024-10-10 15:05 UTC, cwpearson commented on batched/dense/impl/KokkosBatched_QR_FormQ_Serial_Internal.hpp
Can any of these structs be moved to `Impl` while you're at it? e.g. `SerialQR_FormQ_Internal`. Or woudl you prefer to do that as a separate deprecating PR?

2024-10-10 15:05 UTC, cwpearson commented on batched/dense/unit_test/Test_Batched_SerialQR.hpp
> +// #if defined(KOKKOSKERNELS_INST_COMPLEX_FLOAT)
Leave an explanation for why this is disabled.

2025-03-08 04:15 UTC, yasahi-hpc requested changes
I requested small changes. I also have three additional points.

1. It seems that `Side::Right` specialization of `KokkosBatched::SerialApplyQ` is not tested. Is it possible to add a test case for this specialization?
2. Could you also consider to add docstrings in APIs under `KokkosBatched_ApplyQ_Decl.hpp` and `KokkosBatched_QR_Decl.hpp`? It would be helpful to generate API reference
3. Could you also add `static_assertion` to check the template argument is valid, e.g., check if `ArgTrans` is `NoTranspose` or `Transpose`.

2025-03-10 17:25 UTC, lucbv commented on batched/dense/unit_test/Test_Batched_SerialQR.hpp
> +    constexpr double max_val = 1000;
Same logic as previously stated applies and on this one I would be even stricter, I absolutely want the compiler to warn us if in the future someone tries to const_cast that away as it means they are messing with the analytical formula for the tolerance check

2025-03-10 17:30 UTC, lucbv commented on batched/dense/unit_test/Test_Batched_SerialQR.hpp
> +  constexpr int m = 3, n = 2;
Still objecting

2025-03-10 23:23 UTC, lucbv commented
I addressed 1. and 3. however for the documentation I will delay until we have it setup in the repo for batched algorithms.
This should not take too long as I am in the process of writing the main page for that and then we will be able to add the APIs one by one as we get to them.

2025-03-11 05:05 UTC, yasahi-hpc approved these changes
LGTM. 
As for the documentation, I can contribute if needed. 
Let me know if you decided how to implement.

2025-03-11 15:02 UTC, cwpearson approved these changes

2025-03-11 15:15 UTC, merged

2025-03-12 00:05 UTC, ndellingwood commented
@lucbv some of these changes were incompatible with usage in Trilinos (intrepid2), this is showing in the nightly integration builds:

```
17:53:56 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_OneAPI2023_2_0_ICPX_Serial/Trilinos/packages/intrepid2/src/Projection/Intrepid2_ProjectionTools.hpp:527:9: error: no member named 'SerialQR_Internal' in namespace 'KokkosBatched'; did you mean 'KokkosBatched::Impl::SerialQR_Internal'?
17:53:56         KokkosBatched::SerialQR_Internal::invoke(A0_host.extent(0), A0_host.extent(1),
17:53:56         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
17:53:56         KokkosBatched::Impl::SerialQR_Internal
17:53:56 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_OneAPI2023_2_0_ICPX_Serial/Trilinos/kokkos-kernels/batched/dense/impl/KokkosBatched_QR_Serial_Internal.hpp:34:8: note: 'KokkosBatched::Impl::SerialQR_Internal' declared here
17:53:56 struct SerialQR_Internal {
17:53:56        ^
17:53:56 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_OneAPI2023_2_0_ICPX_Serial/Build/packages/intrepid2/unit-test/Projection/test_project_fields_Serial_DOUBLE.cpp:15:
17:53:56 In file included from /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_OneAPI2023_2_0_ICPX_Serial/Trilinos/packages/intrepid2/unit-test/Projection/test_project_fields.hpp:34:
17:53:56 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_OneAPI2023_2_0_ICPX_Serial/Trilinos/packages/intrepid2/src/Projection/Intrepid2_ProjectionTools.hpp:583:11: error: no member named 'SerialQR_Internal' in namespace 'KokkosBatched'; did you mean 'KokkosBatched::Impl::SerialQR_Internal'?
17:53:56           KokkosBatched::SerialQR_Internal::invoke(A.extent(0), A.extent(1),
17:53:56           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
17:53:56           KokkosBatched::Impl::SerialQR_Internal
17:53:56 /home/jenkins/blake-new/workspace/KokkosEco_Trilinos_Blake_OneAPI2023_2_0_ICPX_Serial/Trilinos/kokkos-kernels/batched/dense/impl/KokkosBatched_QR_Serial_Internal.hpp:34:8: note: 'KokkosBatched::Impl::SerialQR_Internal' declared here
17:53:56 struct SerialQR_Internal {
```

Should I be able to add a guard on version and include updates to include the Impl namespace to resolve?

2025-03-12 01:02 UTC, ndellingwood commented
Yeah, simple namespace update was all that was needed, PR up https://github.com/trilinos/Trilinos/pull/13876