Prefer `expected == atomic_compare_exchange(ptr, expected, desired)`
kokkos/kokkos-kernels pull request #2387
Opened 2024-10-17 15:05 UTC by dalg24

Rewrote `atomic_compare_exchange_strong(ptr, expected, desired)` to `expected == atomic_compare_exchange(ptr, expected, desired)` as `atomic_compare_exchange_strong` is on its way to be deprecated/removed (see https://github.com/kokkos/kokkos/pull/7458)

2024-10-17 15:10 UTC, lucbv approved these changes

2024-10-17 22:48 UTC, cwpearson requested changes
If I understand correctly, `atomic_compare_exchange_strong` updates the `expected` value (it takes it by reference), whereas `atomic_compare_exchange` does not, so these re-writes are not equivalent.

2024-10-17 22:54 UTC, dalg24 commented
> If I understand correctly, `atomic_compare_exchange_strong` updates the `expected` value (it takes it by reference), whereas `atomic_compare_exchange` does not, so these re-writes are not equivalent.

No, it takes it by value
https://github.com/kokkos/kokkos/blob/3fe17d96d42eb2bd84f1f2a835a2ed0ba87606b6/core/src/Kokkos_Atomics_Desul_Wrapper.hpp#L135-L139
(I know it is confusing.  The desul counterpart does but I will propose to overhaul this later.  It will be transparent to Kokkos.)
The `atomic_compare_exchange` semantics are easier to reason about.  They follow atomicCAS() form CUDA.

2024-10-17 22:57 UTC, dalg24 commented
Here is a link to the latest release (before I started messing with the API) to convince yourself that this is right.
It is unchanged since 4.0

2024-10-18 14:20 UTC, cwpearson approved these changes
I see now, thanks. I'm good with it once the tests are passing! Thanks @dalg24

2024-10-18 17:25 UTC, ndellingwood commented
Lots of failing kokkos-kernels nightlies with e.g.
```
05:34:15 /home/jenkins/blake-new/workspace/KokkosKernels_Nightly_Blake_OneAPI_2023_1_0_Sycl_PV-oneMKL/kokkos-kernels/common/src/KokkosKernels_HashmapAccumulator.hpp:519:23: error: no member named 'atomic_compare_exchange_strong' in namespace 'Kokkos'
05:34:15           if (Kokkos::atomic_compare_exchange_strong(keys + hash, -1, key)) {
```

I'm assuming this PR will resolve them once ready for merge. Cross-referencing https://github.com/kokkos/kokkos/pull/7458

2024-10-18 17:28 UTC, ndellingwood commented
Multiple jobs failing with timeout in the following tests:
```
 	 14 - graph_cuda (Timeout)
	 16 - sparse_cuda (Timeout)
```

**graph_cuda** seems to be hanging in the test
```
 [ RUN      ] Cuda.graph_random_graph_coarsen_double_int_int_TestDevice
```

**sparse_cuda** seems to be hanging in the test
```
[ RUN      ] Cuda.sparse_spgemm_double_int_int_TestDevice
```

2024-10-18 17:32 UTC, dalg24 commented on sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp
> -              break;
ugggg

2024-10-18 17:32 UTC, dalg24 commented on sparse/impl/KokkosSparse_spgemm_impl_kkmem.hpp
>                fail = 0;
```suggestion
              fail = 0;
              break;
```

2024-10-18 17:35 UTC, ndellingwood approved these changes
Tentative approval to trigger AT2

2024-10-18 17:36 UTC, ndellingwood commented
@dalg24 can you add the dco signoff as well (check failed)? Sorry for the inconvenience

2024-10-18 21:49 UTC, merged