Improve batched serial gemm
kokkos/kokkos-kernels pull request #2469
Opened 2024-12-19 07:14 UTC by yasahi-hpc

This PR aims at improving the implementation and testing of serial Gemm.

 - [x] Moving implementation details into `Impl` namespace.
 - [x] Moving `OpID` and `OpConj` into `blas/impl/KokkosBlas_util.hpp`
 - [x] Add all the specializations of the combinations of `Non-Trans/Trans/ConjTrans`
 - [x] Add a check function of input to force A, B, C are rank 0, 1, 2 `Kokkos::View`
 - [x] Covering all the unit-tests for all the combinations of `Non-Trans/Trans/ConjTrans`
 - [x] Deprecated warnings for the older implementation details under `KokkosBatched` namespace

2025-01-06 17:19 UTC, cwpearson requested changes

2025-01-06 17:19 UTC, cwpearson commented on common/src/KokkosKernels_BlockUtils.hpp
> +  DGEMM::invoke(KokkosBlas::Impl::OpID(), KokkosBlas::Impl::OpID(), block_dim, block_dim, block_dim, ONE, valA,
I'm confused about how calling `OpID()` here with no arguments works. It looks like it must take a value.

2025-01-06 17:59 UTC, yasahi-hpc commented on common/src/KokkosKernels_BlockUtils.hpp
> +  DGEMM::invoke(KokkosBlas::Impl::OpID(), KokkosBlas::Impl::OpID(), block_dim, block_dim, block_dim, ONE, valA,
Thank you for the comments. 
I am doing exactly the same thing as in gemv. Basically, I am just passing a temporary object of `OpID()` class.

https://github.com/kokkos/kokkos-kernels/blob/85bbf1ff4aba86881c6bd65e8b00ec2fd21d6e9e/blas/impl/KokkosBlas2_serial_gemv_impl.hpp#L91-L107

2025-01-07 09:01 UTC, yasahi-hpc commented
@cwpearson I have removed the global namespace following your suggestions for #2331 
I have also confirmed that Trilinos does not rely on the implementation details directly. 
I am worried about the potential usage of the APIs with `DynRankViews` though

2025-01-07 14:12 UTC, lucbv commented on common/src/KokkosKernels_BlockUtils.hpp
> +  DGEMM::invoke(KokkosBlas::Impl::OpID(), KokkosBlas::Impl::OpID(), block_dim, block_dim, block_dim, ONE, valA,
To be clear, in that spot Yuuichi is calling the constructor not `operator()` so that should work fine.

2025-01-07 14:18 UTC, lucbv commented on batched/dense/unit_test/Test_Batched_SerialGemm.hpp
> +  eps *= std::is_same_v<ValueType, Kokkos::Experimental::half_t> ||
This definition of epsilon worries me a bit, we should revisit to actually compute the expected accuracy based on the compute parameters chosen for the test...

2025-01-07 14:21 UTC, lucbv approved these changes
The changes look fine to me, let's run this through the auto-tester.

2025-01-07 16:03 UTC, cwpearson commented
> @cwpearson I have removed the global namespace following your suggestions for #2331 I have also confirmed that Trilinos does not rely on the implementation details directly. I am worried about the potential usage of the APIs with `DynRankViews` though

There's `Kokkos::is_dyn_rank_view_v` if you want to modify the static asserts, or are you worried for another reason?

2025-01-07 16:03 UTC, cwpearson approved these changes

2025-01-08 06:00 UTC, yasahi-hpc commented
> > @cwpearson I have removed the global namespace following your suggestions for #2331 I have also confirmed that Trilinos does not rely on the implementation details directly. I am worried about the potential usage of the APIs with `DynRankViews` though
> 
> There's `Kokkos::is_dyn_rank_view_v` if you want to modify the static asserts, or are you worried for another reason?

I personally prefer not to allow `DynRankViews` because we cannot check ranks of `DynRankViews` at compile time.

2025-01-09 18:09 UTC, merged